services:
  polybot:
    image: ${IMG_NAME}
    restart: always
    ports:
      - "8080:8080"
    env_file: .env
    networks:
      - observability
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 5

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
    command: ["--config", "/etc/otelcol/config.yaml"]
    ports:
      - "8889:8889"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
      - /proc:/host_proc:ro
      - /sys:/host_sys:ro
    environment:
      - HOST_PROC=/host_proc
      - HOST_SYS=/host_sys
    network_mode: host
    depends_on:
      polybot:
        condition: service_healthy

networks:
  observability: