version: '3.8'

services:
  polybot:
    image: "${IMG_NAME}"
    container_name: polybot-container
    environment:
      - TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
      - BOT_APP_URL=${{ secrets.BOT_APP_URL }}
      - YOLO_SERVER_URL=${{ secrets.YOLO_SERVER_URL }}
      - S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
      - OTEL_SERVICE_NAME=polybot
      - OTEL_EXPORTER=prometheus
      - OTEL_EXPORTER_PROMETHEUS_PORT=8889
    ports:
      - "8080:8080"
      - "8889:8889"  # Exposing Prometheus metrics endpoint for monitoring
    volumes:
      - .:/app
    restart: always

  otelcol:
    image: "otel/opentelemetry-collector:latest"
    container_name: otelcol
    command: ["--config", "/etc/otelcol-config.yaml"]
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-config.yaml
    ports:
      - "8889:8889"  # Port for Prometheus metrics collection
    restart: always
