receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      load:
      network:
      paging:
      processes:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [prometheus]

#receivers:
#  # Receives Prometheus metrics from Polybot
#  prometheus:
#    config:
#      scrape_configs:
#        - job_name: 'polybot'
#          static_configs:
#            - targets: ['polybot:8080'] # Polybot's metrics endpoint
#
#  # Collects host metrics
#  hostmetrics:
#    collection_interval: 10s
#    root_path: /host_proc
#    scrapers:
#      cpu:
#      memory:
#      disk:
#      filesystem:
#      load:
#      network:
#
#exporters:
#  # Exports Prometheus metrics to the Prometheus server
#  prometheus:
#    endpoint: "0.0.0.0:8889" # Prometheus metrics endpoint exposed on port 8889
#
#service:
#  pipelines:
#    # Collects and exports metrics from Polybot container and host
#    metrics:
#      receivers: [prometheus, hostmetrics]
#      exporters: [prometheus]