name: Polybot Build Prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build_and_push.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Image
        id: build_and_push
        run: |
          img=nataliea7/polybot-dev:${{ github.run_number }}
          docker build -t $img .
          docker push $img
          echo "image=$img" >> "$GITHUB_OUTPUT"

      - name: Confirm output
        run: |
          echo "Built image: ${{ steps.build_and_push.outputs.image }}"

  deploy:
    needs: build
    uses: ./.github/workflows/deployment-prod.yaml

    with:
      image: nataliea7/polybot-prod:${{ github.run_number }}

    secrets:
      SSH_PRIVATE_KEY_PROD: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
      PROD_POLYBOT_HOST: ${{ secrets.PROD_POLYBOT_HOST }}
      TELEGRAM_BOT_TOKEN_PROD: ${{ secrets.TELEGRAM_BOT_TOKEN_PROD }}
      USERNAME: ${{ secrets.USERNAME }}
      BOT_APP_URL: ${{ secrets.BOT_APP_URL_PROD }}
      YOLO_SERVER_URL: ${{ secrets.YOLO_SERVER_URL_PROD }}
      S3_BUCKET_NAME_PROD: ${{ secrets.S3_BUCKET_NAME_PROD }}
      REGION: ${{ secrets.REGION }}
#      SQS_URL_DEV: ${{ secrets.SQS_URL_DEV }}
#      TABLE_NAME_DEV: ${{ secrets.TABLE_NAME_DEV }}
